server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/task
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
openai:
  api:
    key: ${OPENAI_API_KEY}
